runtime: python39
instance_class: F1
entrypoint: gunicorn -b :$PORT 'app:create_app()'

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 10

env_variables:
  CLIENT_ID: ""
  LOGIN_URI: "https://YOUR_URI/login/callback"
  SECRET_KEY: ""

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: auto
